config/routes.rb
Blogger::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "home#index"

  resources :blog_posts, only: [:index, :show]
  resources :tags, only: [:show]

  post 'send_email' => 'emails#create', as: 'send_email'
  get 'search' => 'searches#find', as: 'search'
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  include Taggable
  include Searchable
  extend FriendlyId

  friendly_id :title, use: :slugged

  attr_accessible :title,
                  :body,
                  :published_at,
                  :tag_list,
                  :tag_ids,
                  :summary,
                  :blog_category_id,
                  :photo,
                  :published

  belongs_to :blog_category
  belongs_to :author, class_name: "AdminUser", foreign_key: 'admin_user_id'
  has_many :taggings
  has_many :tags, through: :taggings

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "150x150>" },
                            :url  => "/assets/images/uploads/:style/:basename.:extension",
                            :path => ":rails_root/app/assets/images/uploads/:style/:basename.:extension"

  before_save :update_published_at, if: Proc.new { |i| i.published_changed? }
  after_save :index_for_search

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  scope :recent, ->(*args) { where("created_at > ?", args.first || 6.months.ago ).order("created_at DESC") }
  scope :published, -> { where(published: true) }

  settings do
    mappings do
      indexes :id, :index => :no
      # Search these fields
      indexes :title, analyzer: :english
      indexes :summary, analyzer: :english
      indexes :body, analyzer: :english
      indexes :published_at
      # relationships
      indexes :tag_list, analyzer: :english
    end
  end

  def pretty_published_at
    published_at ? published_at.strftime('%m/%d/%Y') : nil
  end

  def index_for_search
    if published?
      index_document
    else
      delete_document
    end rescue nil # rescue if not indexed
  end

  def as_indexed_json(options = {})
     as_json(
       only: [ :id, :created_at, :title, :summary, :body, :published_at ],
       methods: [ :tag_list ]
     )
  end

  def update_published_at
    self.published_at = published ? Time.now : nil
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  def index
    @categories = BlogCategory.with_published_posts.includes(:tags)
    posts = BlogPost.published.order("published_at DESC")
    @posts = Kaminari.paginate_array(posts).page(params[:page]).per(5)
  end

  def show
    @post = BlogPost.includes(:tags).find(params[:id])
  end

end

app/helpers/blog_post_helper.rb
module BlogPostHelper
  def highlight(post, attribute)
    display = ''
    if post.respond_to?("hi_#{attribute.to_s}")
      display = (post.send("hi_#{attribute.to_s}") || post.send(attribute))
    else
      display = post.send(attribute)
    end
    text = display.is_a?(String) ? display : display.join("\n")
    text.html_safe
  end

end

app/views/blog_posts/_tag_well.html.haml
%div.tag-cloud
  - tag_cloud category.tags, %w(small medium large) do |tag, css_class|
    %div.tag
      = link_to tag.name, tag_path(tag), class: css_class

app/views/blog_posts/index.html.haml
= content_for(:title, "Blog Posts")

%div.row
  %div.large-12.columns.panel.blog-banner.hide-for-small
    - if @tag
      = "Tagged with #{@tag.name}"
    - else
      Welcome to the scary place that is my thoughts...

%div.row{style: 'min-height:65%;'}
  = render partial: 'shared/tag_cloud', locals: {categories: @categories}
  = render partial: 'shared/blog_posts', locals: {posts: @posts}

app/views/blog_posts/show.html.haml
= content_for(:title, @post.title)
= meta_tag(:description, @post.summary)
= meta_tag(:keywords, @post.tags.pluck(:name).join(','))

%div.row{ style: "margin-top:25px;" }
  %div.large-12.columns
    %div.panel
      %h1.blog-banner= @post.title
      %p= @post.summary

%div.row
  %div.large-1.columns.small-3
    = image_link(@post.photo(:thumb))
  %div.large-11.columns
    = render partial: "shared/markdown_container", locals: { text: @post.body }

    %hr

    #disqus_thread
    :javascript
      /* * * CONFIGURATION VARIABLES * * */
      var disqus_shortname = 'dainjar';

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
    %noscript
      Please enable JavaScript to view the
      %a{:href => "https://disqus.com/?ref_noscript", :rel => "nofollow"} comments powered by Disqus.