config/routes.rb
Blogger::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "home#index"

  resources :blog_posts, only: [:index, :show]
  resources :tags, only: [:show]

  post 'send_email' => 'emails#create', as: 'send_email'
  get 'search' => 'searches#find', as: 'search'
end

app/views/shared/_blog_posts.html.haml
%div.large-9.columns
  %div.row.search-results
    - if posts.blank?
      %p
        Sorry, but we couldn't find anything interesting
    - else
      - posts.each do |post|
        %div.large-1.columns.small-3.hide-for-small
          = image_link(post.photo(:thumb))
        %div.large-11.columns
          %p
            %strong
              = link_to highlight(post, :title), "#{blog_post_path(post)}"
            %br
            ="Published: #{post.pretty_published_at}"
          %p= highlight(post, :summary)
          - if post.respond_to?(:hi_body)
            %p= highlight(post, :body)
          - if post.respond_to?(:hi_tag_list)
            %p= highlight(post, :tag_list)
        %hr
  = paginate posts

app/views/shared/_custom_page_break.html.haml
%div.custom-page-break
  %button.btn-icon{role: "show-more", data: { section: selector } }
    %i.icon-font.down-arrow

app/views/shared/_markdown.html.haml
.markdowned
  = preserve markdown(text) if text

app/views/shared/_markdown_container.html.haml
.markdown-container{role: "markdown-container"}
  .markdowned
    = preserve markdown(text) if text

app/views/shared/_search_form.html.haml
%div.large-12.columns.large-centered
  %div{ class: "row collapse postfix-round" }
    = simple_form_for :search, url: search_path, method: 'get' do |f|
      %div{ class: "small-10 columns", style: 'padding-right:0;' }
        = f.input :text, label: false, input_html: { placeholder: 'Search Here' }
      %div{ class: "small-2 columns",  style: 'padding-left:0;' }
        = f.button :submit, "Go", class: "button postfix"

app/views/shared/_tag_cloud.html.haml
%div.large-3.columns.panel.hide-for-small
  %h5{style: 'color:black'}= link_to "Topics", "javascript:void(0);"
  %div.tagging-container
    - categories.each_with_index do |category, index|
      %section.tag-category{ role: "expandable" }
        %h5.title= link_to "#{category.name} (#{category.tags.count})", "javascript:void(0);"
        %div{ role: "tag-well", style: "display:none", data: { category_number: index + 1 } }
          = render partial: "blog_posts/tag_well", locals: { category: category }