config/routes.rb
Blogger::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "home#index"

  resources :blog_posts, only: [:index, :show]
  resources :tags, only: [:show]

  post 'send_email' => 'emails#create', as: 'send_email'
  get 'search' => 'searches#find', as: 'search'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    pages = Page.all
    @bio      = select(pages, "Biography")
    @edu      = select(pages, "Education")
    @work     = select(pages, "Work Experience")
    @projects = select(pages, "Projects")

    # implement this
    # @content_areas = [bio, edu, work, projects, skills]

    posts = BlogPost.published.order("published_at DESC").limit(5)

    @image = Photo.find_by_title("skyline")

    @featured_post = posts.shift
    @other_posts = posts unless posts.empty?
  end

  private

  def select(selection, page_name)
    selection.find { |page| page.name == page_name }
  end

end

app/views/home/_carousel.html.haml
%div.orbit-container.large-12.columns
  %ul.example-orbit.orbit-slides-container(data-orbit)
  - @page.images.each_with_index do |image, index|
    - status = index == 0 ? 'active' : 'inactive'
    %li{class: "#{status}"}
      = image_tag image.thumbnail.url, alt: "slide #{index + 1}"
      %div.orbit-caption
        = "Caption #{index + 1}"
  - # Navigation Arrows
  %a
    = link_to "Prev", "#", class: "orbit-prev"
  %a
    = link_to "Next", "#", class: "orbit-next"
  - # Slide Numbers
  %div.orbit-slide-number
    %span 1 of
    %span 3
  - #Timer and Play/Pause Button
  %div.orbit-timer
    %div.orbit-progress
- # Bullets
%ol.orbit-bullets
- @page.images.each_with_index do |image, index|
  - status = index == 0 ? 'active' : 'inactive'
  %li{class: "#{status}", data: {orbit_slide_number: "#{index + 1}"}}

app/views/home/index.html.haml
%div.row.home-body
  %div.large-6.small-12.columns

    %h4 A Little About Me
    %hr

    %div.row
      %div.large-2.columns.hide-for-small
        = image_tag("bio.jpg", class: 'section-image')
      %div.large-10.columns.resume-content{ role: "expandable-content", data: {bio: true} }
        = render partial: "shared/markdown", locals: { text: @bio.body }
    %div.hide-for-small
      = render partial: "shared/custom_page_break", locals: {selector: 'bio'}

    %div.row.hide-for-small
      %div.large-2.columns.text-center
        = image_tag("resume.jpg", class: 'section-image')
        %h6 Work
      %div.large-10.columns.resume-content{ role: "expandable-content", data: {resume: true} }
        = render partial: "shared/markdown", locals: { text: @work.body }
    %div.hide-for-small
      = render partial: "shared/custom_page_break", locals: {selector: 'resume'}

    %div.row.hide-for-small
      %div.large-2.columns.text-center
        = image_tag("education.jpg", class: 'section-image')
        %h6 Education
      %div.large-10.columns.resume-content{ role: "expandable-content", data: {education: true} }
        = render partial: "shared/markdown", locals: { text: @edu.body }
    %div.hide-for-small
      = render partial: "shared/custom_page_break", locals: {selector: 'education'}

    %div.row.hide-for-small
      %div.large-2.columns.text-center
        = image_tag("projects.jpg", class: 'section-image')
        %h6 Projects
      %div.large-10.columns.resume-content{ role: "expandable-content", data: {projects: true} }
        = render partial: "shared/markdown", locals: { text: @projects.body }
    %div.hide-for-small
      = render partial: "shared/custom_page_break", locals: {selector: 'projects'}

  %div.large-6.small-12.columns.blog-panel
    %h4 Blog
    %hr
    %div.panel
      %h5= link_to @featured_post.title, blog_post_path(@featured_post)
      %h6= @featured_post.pretty_published_at
      %h6.subheader= @featured_post.summary
      %h6= link_to "Read More »", blog_post_path(@featured_post)
    - if @other_posts.present?
      - @other_posts.each do |post|
        %div.panel.hide-for-small
          %h5= link_to "#{post.title} »", blog_post_path(post)
          %h6= post.pretty_published_at

    =link_to "Go To Blog »", blog_posts_path, class: "right"