config/routes.rb
Blogger::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "home#index"

  resources :blog_posts, only: [:index, :show]
  resources :tags, only: [:show]

  post 'send_email' => 'emails#create', as: 'send_email'
  get 'search' => 'searches#find', as: 'search'
end

app/views/layouts/_footer.html.haml
%link{:href => "http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css", :rel => "stylesheet"}
  %footer.footer
    .row
      .small-12.medium-6.large-6.columns.left
        %p.logo.hide-for-small-only
          LET'S STAY IN TOUCH
        .row
          %ul.social
            %a{:href => "https://www.facebook.com/dainhall?fref=ts"}
              %i.fi-social-facebook
            %a{:href => "https://twitter.com/donelikedainer?lang=en"}
              %i.fi-social-twitter
            %a{:href => "https://www.linkedin.com/profile/view?id=106601609&trk=nav_responsive_tab_profile_pic"}
              %i.fi-social-linkedin
            %a{:href => "https://github.com/daino3"}
              %i.fi-social-github

      .small-12.medium-6.large-6.columns.right
        %p.logo.show-for-small-only
          EMAIL ME
        %div{role: 'email-message-container'}
        = simple_form_for(:email, url: send_email_path, method: 'post', html: {class: 'footer-form row', role: 'email-form'}) do |f|
          .small-12.columns
            = f.input :from, label: false, placeholder: 'Your Email'
          .small-12.columns
            = f.input :subject, label: false, placeholder: 'Subject'
          .small-12.columns
            = f.text_area :body, label: false, placeholder: 'Message'
          .hide
            = f.check_box :bot_box
          .small-12.columns
            = f.submit "Send"

app/views/layouts/_header.html.haml
%div{style: "background-color:black"}
  %nav.top-bar.row{role: "navigation", data: {data: "topbar"}}
    %ul.title-area.large-3.columns{style: "padding:0px"}
      %li.name
        %h1=link_to "Dainger.us", root_path, style: "padding:0px"
      // Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
      %li.toggle-topbar.menu-icon
        %a{href: "#"}
          %span Menu

    %section.top-bar-section.large-6.columns
      = render partial: "shared/search_form"

    %section.top-bar-section.large-3.columns{style: "padding:0px"}
      %ul.right
        %li= link_to "Blog", blog_posts_path, style: "padding:0px"
        %li.divider{style: "width:10px"}
        %li= link_to "Resume", resume_path, target: "_blank"

app/views/layouts/_home_header.html.haml
%div.header-container.text-center.image-gradient-dynamic
  = image_tag(@image.get_url, class: "background-image")
  %div.overlay
  %h3.background-image-text.copy
    "A mind that is stretched by new experiences can never return to its original dimensions"

  %div.row.home-header
    %div.large-3.columns.nav-section.site-title
      %h1.home-header-title= link_to "Dainger.us"

    %div.large-5.columns.nav-section.hide-for-small
      = render partial: "shared/search_form"

    %div.large-4.columns.nav-section.nav-section-main.hide-for-small
      %ul.inline-list
        %li= link_to "Blog", blog_posts_path
        %li.divider{style: "width:10px"}
        %li= link_to "Resume", resume_path, target: "_blank"
        %li.divider
  %div.large-4.columns.nav-section-small.show-for-small
    %ul.inline-list
      %li= link_to "Blog", blog_posts_path
      %li= link_to "Resume", resume_path, target: "_blank"

app/views/layouts/_new_header.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h1
        %a{href: "#"} Dainjar.us
    // Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{href: "#"}
        %span Menu

  %section.top-bar-section    
    %ul
      %li.divider.hide-for-small
      %li.has-form
        %form
          %div.row.collapse
            %div.small-8.columns
              %input{type: "text"}
            %div.small-4.columns
              %a{href: "#", class: "alert button"} Search
      
    %ul.right
      %li.divider
      %li
        = link_to "Home", root_path
      %li.divider
      %li
        = link_to "Blog", blog_posts_path
      %li.divider
      %li
        %a{href: "#"} Download Resume
      %li.divider

app/views/layouts/application.html.haml
%head
  %title
    - if content_for?(:title)
      = yield(:title) + " | Dainger.us - Dain Hall's Blog"
    - else
      = "Dainger.us - Dain Hall's Blog"


  %meta{ charset: "utf-8"}
  %meta{ name: "viewport",    content: "width=device-width, initial-scale=1.0"}
  %meta{ name: "description", content: yield_meta_tag(:description, "Dain Hall's blog on software, life, and random thoughts") }
  %meta{ name: "keywords",    content: yield_meta_tag(:keywords, "DainHall,Blog,Software,Life,Work,Play") }
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = csrf_meta_tags

  :javascript
    (function(i,s,o,g,r,a,m){
      i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();
        a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;
        a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-46222711-1', 'auto');
    ga('send', 'pageview');

%body
  - if request.path == root_path
    = render partial: "layouts/home_header"
  - else
    = render partial: "layouts/header"
  = yield
  :javascript
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'dainjar';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    // comment count
    (function () {
       var s = document.createElement('script'); s.async = true;
       s.type = 'text/javascript';
       s.src = '//' + disqus_shortname + '.disqus.com/count.js';
       (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
%footer
  = render partial: "layouts/footer"